apiVersion: v1
kind: Service
metadata:
  name: gotenberg
  namespace: paperless
spec:
  selector:
    app: gotenberg
  ports:
    - port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tika
  namespace: paperless
spec:
  selector:
    app: tika
  ports:
    - port: 9998
