apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
  labels:
    homelab/app: pihole
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pihole
        homelab/app: pihole
    spec:
      containers:
      - env:
        - name: FTLCONF_webserver_port
          value: "80"
        - name: VIRTUAL_HOST
          value: pi.hole
        - name: FTLCONF_misc_etc_dnsmasq_d
          value: "true"
        - name: FTLCONF_webserver_api_password
          valueFrom:
            secretKeyRef:
              key: password
              name: pihole-password
        - name: FTLCONF_dns_listeningMode
          value: all
        - name: TZ
          value: "America/Recife"
        - name: FTLCONF_dns_upstreams
          value: 1.1.1.1;9.9.9.9
        - name: FTLCONF_dns_dnssec
          value: "true"
        image: pihole/pihole:2025.07.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /admin
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: pihole
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 53
          name: dns
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 67
          name: client-udp
          protocol: UDP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /admin
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pihole
          name: config
        - mountPath: /etc/dnsmasq.d/02-custom.conf
          name: custom-dnsmasq
          subPath: 02-custom.conf
        - mountPath: /etc/addn-hosts
          name: custom-dnsmasq
          subPath: addn-hosts
        - mountPath: /etc/pihole/adlists.list
          name: adlists
          subPath: adlists.list
      dnsConfig:
        nameservers:
        - 127.0.0.1
        - 8.8.8.8
      dnsPolicy: None
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: pihole
      - configMap:
          defaultMode: 420
          name: pihole-custom-dnsmasq
        name: custom-dnsmasq
      - configMap:
          defaultMode: 420
          name: pihole-adlists
        name: adlists
