services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    environment:
      TZ: America/Recife
      HOMEPAGE_ALLOWED_HOSTS: 192.168.50.100
      PUID: "1000"
      PGID: "1000"
    ports:
      - "80:3000"
    volumes:
      - ./config:/app/config
