- Homelab Dashboard:
    - Unifi:
        href: http://192.168.0.1
        description: Unifi Dream Machine Router.
        icon: unifi
        ping: 192.168.50.1
    - Synology:
        href: http://192.168.50.10:5000
        description: Synology NAS.
        icon: synology
        ping: 192.168.50.10
    - Home Assistant:
        href: http://192.168.40.40
        description: Smart home automation and control.
        icon: home-assistant
        ping: 192.168.40.40
- Proxmox Status:
    - Proxmox pve1:
        href: https://192.168.50.11:8006
        description: Proxmox node.
        icon: proxmox
        ping: 192.168.50.11
    - Proxmox pve2:
        href: https://192.168.50.12:8006
        description: Proxmox node.
        icon: proxmox
        ping: 192.168.50.12
    - Proxmox pve3:
        href: https://192.168.50.13:8006
        description: Proxmox node.
        icon: proxmox
        ping: 192.168.50.13
- Container Status:
    - Pi-hole:
        href: http://192.168.50.100:8080/admin
        description: Network-wide ad blocking and privacy solution.
        icon: pi-hole
        server: local-podman
        container: pihole
    - Deye Dummycloud:
        href: http://192.168.50.100:10000
        description: Deye dummycloud container runtime status.
        icon: mdi-cloud
        server: local-podman
        container: deye-dummycloud
        showStats: false
