apiVersion: v1
kind: Service
metadata:
  labels:
    app: calibre-web
  name: calibre-web
  namespace: calibre-web
spec:
  loadBalancerIP: 192.168.50.103
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: calibre-web
  type: LoadBalancer
