apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-books
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.50.10
    path: /volume1/homelab/apps/calibre/books
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-books
  namespace: calibre-web
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: calibre-books
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
  namespace: calibre-web
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
