apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: paperless
spec:
  selector:
    app: paperless-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: paperless
spec:
  selector:
    app: paperless-redis
  ports:
    - port: 6379
