apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
  labels:
    homelab/app: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
        homelab/app: paperless
    spec:
      containers:
        - name: paperless
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: TZ
              value: "America/Recife"
            - name: PAPERLESS_PORT
              value: "8000"
            - name: PAPERLESS_REDIS
              value: redis://broker:6379
            - name: PAPERLESS_DBHOST
              value: db
            - name: PAPERLESS_TIKA_ENABLED
              value: "1"
            - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
              value: http://gotenberg:3000
            - name: PAPERLESS_TIKA_ENDPOINT
              value: http://tika:9998
          volumeMounts:
            - name: paperless-data
              mountPath: /usr/src/paperless/data
            - name: paperless-media
              mountPath: /usr/src/paperless/media
      volumes:
        - name: paperless-data
          persistentVolumeClaim:
            claimName: paperless-data
        - name: paperless-media
          persistentVolumeClaim:
            claimName: paperless-media
