apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - volumes.yaml
  - ./dependencies/services.yaml
  - ./dependencies/deployments.yaml
  - ./databases/services.yaml
  - ./databases/deployments.yaml
  - service.yaml
  - deployment.yaml
