apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: paperless
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.50.104
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: paperless
