- name: Remove Proxmox enterprise repo file if exists
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
  ignore_errors: yes

- name: Add Proxmox no-subscription repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    regexp: '^deb http://download.proxmox.com/debian/pve'
    line: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
    state: present
    create: yes

- name: Fix Ceph repo to no-subscription
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    regexp: '^deb https://enterprise.proxmox.com/debian/ceph-quincy'
    line: 'deb http://download.proxmox.com/debian/ceph-quincy bookworm main'
    create: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
