apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
data:
  kubernetes.yaml: ""
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Homelab Dashboard:
        - Unifi:
            href: http://192.168.0.1
            description: Unifi Dream Machine Router.
            icon: unifi

        - Synology:
            href: http://192.168.50.10:5000
            description: Synology NAS.
            icon: synology

        - Proxmox:
            href: https://192.168.50.11:8006
            description: VM management.
            icon: proxmox

        - Pi-hole:
            href: http://192.168.50.101/admin
            description: Network-wide ad blocking and privacy solution.
            icon: pi-hole

        - Home Assistant:
            href: http://192.168.40.40
            description: Smart home automation and control.
            icon: home-assistant

        - Immich:
            href: https://192.168.50.102
            description: Photo and media management platform.
            icon: immich

        - Calibre:
            href: http://192.168.50.103
            description: Access your eBook library and manager.
            icon: calibre

        - Paperless:
            href: http://192.168.50.104
            description: Document management.
            icon: paperless
  widgets.yaml: ""
  docker.yaml: ""
