apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.50.100
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: homepage
