- name: Proxmox Cluster Setup
  hosts: proxmox
  become: yes
  gather_facts: false

  tasks:
    # copy-ssh-keys and create cluster setup will freeze because of master node password, do it manually
    # - import_tasks: tasks/01-copy-ssh-keys.yaml
    # - import_tasks: tasks/02-create-cluster.yaml 
    - import_tasks: tasks/03-add-nfs.yaml
    - import_tasks: tasks/04-enable-ha.yaml
    - import_tasks: tasks/05-switch-to-no-subscription.yaml
    - import_tasks: tasks/06-setup-autoboot-service.yaml
    - import_tasks: tasks/07-disable-subscription-popup.yaml

